### ISSUE TITLE
备用地址挂了

### ISSUE THREAD

**Issue by Cynun** [woct0rdho/project-asteria#1]
如题，备用地址已经无法访问。

**Comment by woct0rdho** [comment]
你说 https://mega.nz/#F!dIM2AY5D!u2FKDMgruY9l6l8znshkfw 这个地址吗，我这边试了一下没问题

**Comment by Cynun** [comment]
是的，我在中国大陆，运营商为中国联通，结果是无法访问。

实际上，整个大陆地区似乎都无法访问mega.nz😂
![image](https://github.com/woct0rdho/project-asteria/assets/110143030/42b5cb8e-c515-43f5-8191-31b2d1eef56e)

**Comment by woct0rdho** [comment]
那我在百度盘传一份吧，但是我也不知道能活多久

https://pan.baidu.com/s/1yJquekA0sOWXoo2vt0SMug?pwd=pac7

**Comment by Cynun** [comment]
可以打开了，非常感谢！
